/*
 * GTPInformationElements.cpp -- part of Captool, a traffic profiling framework
 *
 * Copyright (C) 2009, 2010 Ericsson AB
 */

#include <cassert>

#include "GTPInformationElements.h"

using std::string;

GTPInformationElements::GTPInformationElements()
{
    _validInformationElements[0] = false;
    _validInformationElements[1] = true;
    _validInformationElements[2] = true;
    _validInformationElements[3] = true;
    _validInformationElements[4] = true;
    _validInformationElements[5] = true;
    _validInformationElements[6] = false;
    _validInformationElements[7] = false;
    _validInformationElements[8] = true;
    _validInformationElements[9] = true;
    _validInformationElements[10] = false;
    _validInformationElements[11] = true;
    _validInformationElements[12] = true;
    _validInformationElements[13] = true;
    _validInformationElements[14] = true;
    _validInformationElements[15] = true;
    _validInformationElements[16] = true;
    _validInformationElements[17] = true;
    _validInformationElements[18] = true;
    _validInformationElements[19] = true;
    _validInformationElements[20] = true;
    _validInformationElements[21] = true;
    _validInformationElements[22] = true;
    _validInformationElements[23] = true;
    _validInformationElements[24] = true;
    _validInformationElements[25] = true;
    _validInformationElements[26] = true;
    _validInformationElements[27] = true;
    _validInformationElements[28] = true;
    _validInformationElements[29] = true;
    _validInformationElements[30] = false;
    _validInformationElements[31] = false;
    _validInformationElements[32] = false;
    _validInformationElements[33] = false;
    _validInformationElements[34] = false;
    _validInformationElements[35] = false;
    _validInformationElements[36] = false;
    _validInformationElements[37] = false;
    _validInformationElements[38] = false;
    _validInformationElements[39] = false;
    _validInformationElements[40] = false;
    _validInformationElements[41] = false;
    _validInformationElements[42] = false;
    _validInformationElements[43] = false;
    _validInformationElements[44] = false;
    _validInformationElements[45] = false;
    _validInformationElements[46] = false;
    _validInformationElements[47] = false;
    _validInformationElements[48] = false;
    _validInformationElements[49] = false;
    _validInformationElements[50] = false;
    _validInformationElements[51] = false;
    _validInformationElements[52] = false;
    _validInformationElements[53] = false;
    _validInformationElements[54] = false;
    _validInformationElements[55] = false;
    _validInformationElements[56] = false;
    _validInformationElements[57] = false;
    _validInformationElements[58] = false;
    _validInformationElements[59] = false;
    _validInformationElements[60] = false;
    _validInformationElements[61] = false;
    _validInformationElements[62] = false;
    _validInformationElements[63] = false;
    _validInformationElements[64] = false;
    _validInformationElements[65] = false;
    _validInformationElements[66] = false;
    _validInformationElements[67] = false;
    _validInformationElements[68] = false;
    _validInformationElements[69] = false;
    _validInformationElements[70] = false;
    _validInformationElements[71] = false;
    _validInformationElements[72] = false;
    _validInformationElements[73] = false;
    _validInformationElements[74] = false;
    _validInformationElements[75] = false;
    _validInformationElements[76] = false;
    _validInformationElements[77] = false;
    _validInformationElements[78] = false;
    _validInformationElements[79] = false;
    _validInformationElements[80] = false;
    _validInformationElements[81] = false;
    _validInformationElements[82] = false;
    _validInformationElements[83] = false;
    _validInformationElements[84] = false;
    _validInformationElements[85] = false;
    _validInformationElements[86] = false;
    _validInformationElements[87] = false;
    _validInformationElements[88] = false;
    _validInformationElements[89] = false;
    _validInformationElements[90] = false;
    _validInformationElements[91] = false;
    _validInformationElements[92] = false;
    _validInformationElements[93] = false;
    _validInformationElements[94] = false;
    _validInformationElements[95] = false;
    _validInformationElements[96] = false;
    _validInformationElements[97] = false;
    _validInformationElements[98] = false;
    _validInformationElements[99] = false;
    _validInformationElements[100] = false;
    _validInformationElements[101] = false;
    _validInformationElements[102] = false;
    _validInformationElements[103] = false;
    _validInformationElements[104] = false;
    _validInformationElements[105] = false;
    _validInformationElements[106] = false;
    _validInformationElements[107] = false;
    _validInformationElements[108] = false;
    _validInformationElements[109] = false;
    _validInformationElements[110] = false;
    _validInformationElements[111] = false;
    _validInformationElements[112] = false;
    _validInformationElements[113] = false;
    _validInformationElements[114] = false;
    _validInformationElements[115] = false;
    _validInformationElements[116] = false;
    _validInformationElements[117] = false; /* reserved for GTP' */
    _validInformationElements[118] = false; /* reserved for GTP' */
    _validInformationElements[119] = false; /* reserved for GTP' */
    _validInformationElements[120] = false; /* reserved for GTP' */
    _validInformationElements[121] = false; /* reserved for GTP' */
    _validInformationElements[122] = false; /* reserved for GTP' */
    _validInformationElements[123] = false; /* reserved for GTP' */
    _validInformationElements[124] = false; /* reserved for GTP' */
    _validInformationElements[125] = false; /* reserved for GTP' */
    _validInformationElements[126] = false; /* reserved for GTP' */
    _validInformationElements[127] = true;
    _validInformationElements[128] = true;
    _validInformationElements[129] = true;
    _validInformationElements[130] = true;
    _validInformationElements[131] = true;
    _validInformationElements[132] = true;
    _validInformationElements[133] = true;
    _validInformationElements[134] = true;
    _validInformationElements[135] = true;
    _validInformationElements[136] = true;
    _validInformationElements[137] = true;
    _validInformationElements[138] = true;
    _validInformationElements[139] = true;
    _validInformationElements[140] = true;
    _validInformationElements[141] = true;
    _validInformationElements[142] = true;
    _validInformationElements[143] = true;
    _validInformationElements[144] = true;
    _validInformationElements[145] = true;
    _validInformationElements[146] = true;
    _validInformationElements[147] = true;
    _validInformationElements[148] = true;
    _validInformationElements[149] = true;
    _validInformationElements[150] = true;
    _validInformationElements[151] = true;
    _validInformationElements[152] = true;
    _validInformationElements[153] = true;
    _validInformationElements[154] = true;
    _validInformationElements[155] = true;
    _validInformationElements[156] = true;
    _validInformationElements[157] = true;
    _validInformationElements[158] = true;
    _validInformationElements[159] = true;
    _validInformationElements[160] = true;
    _validInformationElements[161] = true;
    _validInformationElements[162] = true;
    _validInformationElements[163] = true;
    _validInformationElements[164] = true;
    _validInformationElements[165] = true;
    _validInformationElements[166] = true;
    _validInformationElements[167] = true;
    _validInformationElements[168] = true;
    _validInformationElements[169] = true;
    _validInformationElements[170] = true;
    _validInformationElements[171] = true;
    _validInformationElements[172] = true;
    _validInformationElements[173] = true;
    _validInformationElements[174] = true;
    _validInformationElements[175] = true;
    _validInformationElements[176] = true;
    _validInformationElements[177] = true;
    _validInformationElements[178] = true;
    _validInformationElements[179] = true;
    _validInformationElements[180] = true;
    _validInformationElements[181] = true;
    _validInformationElements[182] = true;
    _validInformationElements[183] = true;
    _validInformationElements[184] = true;
    _validInformationElements[185] = false;
    _validInformationElements[186] = false;
    _validInformationElements[187] = false;
    _validInformationElements[188] = false;
    _validInformationElements[189] = false;
    _validInformationElements[190] = false;
    _validInformationElements[191] = false;
    _validInformationElements[192] = false;
    _validInformationElements[193] = false;
    _validInformationElements[194] = false;
    _validInformationElements[195] = false;
    _validInformationElements[196] = false;
    _validInformationElements[197] = false;
    _validInformationElements[198] = false;
    _validInformationElements[199] = false;
    _validInformationElements[200] = false;
    _validInformationElements[201] = false;
    _validInformationElements[202] = false;
    _validInformationElements[203] = false;
    _validInformationElements[204] = false;
    _validInformationElements[205] = false;
    _validInformationElements[206] = false;
    _validInformationElements[207] = false;
    _validInformationElements[208] = false;
    _validInformationElements[209] = false;
    _validInformationElements[210] = false;
    _validInformationElements[211] = false;
    _validInformationElements[212] = false;
    _validInformationElements[213] = false;
    _validInformationElements[214] = false;
    _validInformationElements[215] = false;
    _validInformationElements[216] = false;
    _validInformationElements[217] = false;
    _validInformationElements[218] = false;
    _validInformationElements[219] = false;
    _validInformationElements[220] = false;
    _validInformationElements[221] = false;
    _validInformationElements[222] = false;
    _validInformationElements[223] = false;
    _validInformationElements[224] = false;
    _validInformationElements[225] = false;
    _validInformationElements[226] = false;
    _validInformationElements[227] = false;
    _validInformationElements[228] = false;
    _validInformationElements[229] = false;
    _validInformationElements[230] = false;
    _validInformationElements[231] = false;
    _validInformationElements[232] = false;
    _validInformationElements[233] = false;
    _validInformationElements[234] = false;
    _validInformationElements[235] = false;
    _validInformationElements[236] = false;
    _validInformationElements[237] = false;
    _validInformationElements[238] = false;
    _validInformationElements[239] = false; /* reserved for GTP' */
    _validInformationElements[240] = false; /* reserved for GTP' */
    _validInformationElements[241] = false; /* reserved for GTP' */
    _validInformationElements[242] = false; /* reserved for GTP' */
    _validInformationElements[243] = false; /* reserved for GTP' */
    _validInformationElements[244] = false; /* reserved for GTP' */
    _validInformationElements[245] = false; /* reserved for GTP' */
    _validInformationElements[246] = false; /* reserved for GTP' */
    _validInformationElements[247] = false; /* reserved for GTP' */
    _validInformationElements[248] = false; /* reserved for GTP' */
    _validInformationElements[249] = false; /* reserved for GTP' */
    _validInformationElements[250] = false; /* reserved for GTP' */
    _validInformationElements[251] = true;
    _validInformationElements[252] = false; /* reserved for GTP' */
    _validInformationElements[253] = false; /* reserved for GTP' */
    _validInformationElements[254] = false; /* reserved for GTP' */
    _validInformationElements[255] = true; /* private extension */

    _informationElementTVLengths[1] = 1;
    _informationElementTVLengths[2] = 8;
    _informationElementTVLengths[3] = 6;
    _informationElementTVLengths[4] = 4;
    _informationElementTVLengths[5] = 4;
    _informationElementTVLengths[8] = 1;
    _informationElementTVLengths[9] = 28;
    _informationElementTVLengths[11] = 1;
    _informationElementTVLengths[12] = 3;
    _informationElementTVLengths[13] = 1;
    _informationElementTVLengths[14] = 1;
    _informationElementTVLengths[15] = 1;
    _informationElementTVLengths[16] = 4;
    _informationElementTVLengths[17] = 4;
    _informationElementTVLengths[18] = 5;
    _informationElementTVLengths[19] = 1;
    _informationElementTVLengths[20] = 1;
    _informationElementTVLengths[21] = 1;
    _informationElementTVLengths[22] = 9;
    _informationElementTVLengths[23] = 1;
    _informationElementTVLengths[24] = 1;
    _informationElementTVLengths[25] = 2;
    _informationElementTVLengths[26] = 2;
    _informationElementTVLengths[27] = 2;
    _informationElementTVLengths[28] = 2;
    _informationElementTVLengths[29] = 1;
    _informationElementTVLengths[127] = 4;

    _informationElementNames[1] = string("Cause");
    _informationElementNames[2] = string("International Mobile Subscriber Identity (IMSI)");
    _informationElementNames[3] = string("Routeing Area Identity (RAI)");
    _informationElementNames[4] = string("Temporary Logical Link Identity (TLLI)");
    _informationElementNames[5] = string("Packet TMSI (P-TMSI)");
    _informationElementNames[8] = string("Reordering Required");
    _informationElementNames[9] = string("Authentication Triplet");
    _informationElementNames[11] = string("MAP Cause");
    _informationElementNames[12] = string("P-TMSI Signature");
    _informationElementNames[13] = string("MS Validated");
    _informationElementNames[14] = string("Recovery");
    _informationElementNames[15] = string("Selection Mode");
    _informationElementNames[16] = string("Tunnel Endpoint Identifier Data I");
    _informationElementNames[17] = string("Tunnel Endpoint Identifier Control Plane");
    _informationElementNames[18] = string("Tunnel Endpoint Identifier Data II");
    _informationElementNames[19] = string("Teardown Ind");
    _informationElementNames[20] = string("NSAPI");
    _informationElementNames[21] = string("RANAP Cause");
    _informationElementNames[22] = string("RAB Context");
    _informationElementNames[23] = string("Radio Priority SMS");
    _informationElementNames[24] = string("Radio Priority");
    _informationElementNames[25] = string("Packet Flow Id");
    _informationElementNames[26] = string("Charging Characteristics");
    _informationElementNames[27] = string("Trace Reference");
    _informationElementNames[28] = string("Trace Type");
    _informationElementNames[29] = string("MS Not Reachable Reason");
    _informationElementNames[127] = string("Charging ID");
    _informationElementNames[128] = string("End User Address");
    _informationElementNames[129] = string("MM Context");
    _informationElementNames[130] = string("PDP Context");
    _informationElementNames[131] = string("Access Point Name");
    _informationElementNames[132] = string("Protocol Configuration Options");
    _informationElementNames[133] = string("GSN Address");
    _informationElementNames[134] = string("MS International PSTN/ISDN Number (MSISDN)");
    _informationElementNames[135] = string("Quality of Service Profile");
    _informationElementNames[136] = string("Authentication Quintuplet");
    _informationElementNames[137] = string("Traffic Flow Template");
    _informationElementNames[138] = string("Target Identification");
    _informationElementNames[139] = string("UTRAN Transparent Container");
    _informationElementNames[140] = string("RAB Setup Information");
    _informationElementNames[141] = string("Extension Header Type List");
    _informationElementNames[142] = string("Trigger Id");
    _informationElementNames[143] = string("OMC Identity");
    _informationElementNames[144] = string("RAN Transparent Container");
    _informationElementNames[145] = string("PDP Context Prioritization");
    _informationElementNames[146] = string("Additional RAB Setup Information");
    _informationElementNames[147] = string("SGSN Number");
    _informationElementNames[148] = string("Common Flags");
    _informationElementNames[149] = string("APN Restriction");
    _informationElementNames[150] = string("Radio Priority LCS");
    _informationElementNames[151] = string("RAT Type");
    _informationElementNames[152] = string("User Location Information");
    _informationElementNames[153] = string("MS Time Zone");
    _informationElementNames[154] = string("IMEI(SV)");
    _informationElementNames[155] = string("CAMEL Charging Information Container");
    _informationElementNames[156] = string("MBMS UE Context");
    _informationElementNames[157] = string("Temporary Mobile Group Identity (TMGI)");
    _informationElementNames[158] = string("RIM Routing Address");
    _informationElementNames[159] = string("MBMS Protocol Configuration Options");
    _informationElementNames[160] = string("MBMS Service Area");
    _informationElementNames[161] = string("Source RNC PDCP context info");
    _informationElementNames[162] = string("Additional Trace Info");
    _informationElementNames[163] = string("Hop Counter");
    _informationElementNames[164] = string("Selected PLMN ID");
    _informationElementNames[165] = string("MBMS Session Identifier");
    _informationElementNames[166] = string("MBMS 2G/3G Indicator");
    _informationElementNames[167] = string("Enhanced NSAPI");
    _informationElementNames[168] = string("MBMS Session Duration");
    _informationElementNames[169] = string("Additional MBMS Trace Info");
    _informationElementNames[170] = string("MBMS Session Repetition Number");
    _informationElementNames[171] = string("MBMS Time To Data Transfer");
    _informationElementNames[173] = string("BSS Container");
    _informationElementNames[174] = string("Cell Identification");
    _informationElementNames[175] = string("PDU Numbers");
    _informationElementNames[176] = string("BSSGP Cause");
    _informationElementNames[177] = string("Required MBMS bearer capabilities");
    _informationElementNames[178] = string("RIM Routing Address Discriminator");
    _informationElementNames[179] = string("List of set-up PFCs");
    _informationElementNames[180] = string("PS Handover XID Parameters");
    _informationElementNames[251] = string("Charging Gateway Address");
    _informationElementNames[255] = string("Private Extension");
}

GTPInformationElements::~GTPInformationElements()
{
}
